# Resolve react_native_pods.rb with node to allow for hoisting.
# Fall back to the default local node_modules path when node is unavailable.
react_native_pods_path = begin
  Pod::Executable.execute_command('node', ['-p',
    'require.resolve(
      "react-native/scripts/react_native_pods.rb",
      {paths: [process.argv[1]]},
    )', __dir__]).strip
rescue Exception
  File.expand_path('../node_modules/react-native/scripts/react_native_pods.rb', __dir__)
end
require react_native_pods_path

platform :ios, '15.5'
$iOSVersion = '15.5'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'DanceFrame' do
  config = use_native_modules!

  pod 'GoogleMLKit/PoseDetection', '8.0.0'
  pod 'GoogleMLKit/PoseDetectionAccurate', '8.0.0'

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer.pods_project.build_configurations.each do |build_configuration|
      build_configuration.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $iOSVersion
      build_configuration.build_settings["EXCLUDED_ARCHS[sdk=*]"] = "armv7"
    end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_configuration|
        if Gem::Version.new($iOSVersion) > Gem::Version.new(build_configuration.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
          build_configuration.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $iOSVersion
        end

        # react-native-svg can fail with non-modular include warnings as errors
        # in some New Architecture iOS simulator builds.
        if target.name == 'RNSVG'
          build_configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        end
      end
    end
  end
end
